- name: PLAY-1 
  hosts: web
  tasks:
    - name: print the msessage PLAY-1 and TASK-1
      ansible.builtin.debug:
      msg: This message is from PLAY-1 and TASK-1 
    
- name: PLAY-2 
  hosts: web
  tasks:
    - name: print the message PLAY-2 and TASK-1
      ansible.builtin.debug:
      msg: This message is from PLAY-2 and TASK-1 