- name: conditions
  hosts: localhost
  become: yes
  tasks:
  - name: conditions
    ansible.builtin.command: id expense
    ignore_errors: true

  - name: print
    ansible.builtin.debug:
      msg: "HELLO"