- name: conditions
  hosts: localhost
  become: yes
  tasks:
  - name: conditions
    ansible.builtin.command: id expense
    register: USER 
    ignore_errors: true 
    

  - name: adding user
    ansible.buitlin.command: useradd expense
    when: USER.rc != 0

  - name: print
    ansible.builtin.debug:
      msg: "HELLO"