- name: default value
  hosts: localhost
  tasks:
  - name: printing the default value
    ansible.builtin.debug:
      msg: "Hello {{Course | default ('Ansible') }}" 

- name: upper case
  hosts: localhost
  vars:
    greetings: "good morning" 
  tasks:
  - name: upper case
    ansible.builtin.debug:
      msg: "{{greetings | upper }}" 

- name: lower case
  hosts: localhost
  vars: 
    greetings: "GOOD MORNING"
  tasks:
  - name: lower case
    ansible.builtin.debug:
      msg: "{{greetings | lower}}"