- name: Installing
  hosts: localhost
  become: yes
  tasks:
  - name: Installing
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: latest
    loop:
    - mysql
    - nginx
    - postfix
